---
title: "covid_model"
author: "Zhimin"
date: "2021/10/14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract
The model combine the idea of ours exponantial model and SIR model. The traditional SIR model has a constant $\beta$ (infection rate) and $\gamma$ recover rate. In ours approach, the infection rate is changing over time with a correlation to different indexs (e.g. government policy).

As the infection rate does not change in a small period of time, the total infected population will follow the exponential model.

## Variable Definitions

$S(t):\: Susceptibles\:population\:at\:time\:t$

$I(t):\: Infected\:population\:at\:time\:t$

$R(t):\:Recovered\:population\:at\:time\:t$

$\beta(t):\:infection\:rate\:at\:time\:t$

$\gamma_i:\:recover\:rate\:after\:being\:infected\:for\:i\:days$

At time $t+1$, the new infected population can be calculated as:

$I(t+1) = \beta(t) *S(t)*I(t)$

At time $t+1$, the new recovered population can be calculated as:

$R(t+1) = \sum_i{\gamma_i * I(t-i)}$

## Model Build Up

Known:

$S(t),I(t),R(t)$ were given from the data.

Coefficient $\gamma_i$ can be calculated using the historical data or medical paper.

Therefore, the real $\beta(t)$ can be calculated after knowing $S(t),I(t),R(t),\gamma_i$.



Unknown:

At time $t=T$, coefficient $\beta(T)$ will be trained using regression models (linear regression, polynomial regressions, etc.)

The index values at time T. Most policy will be moving smoothly, and the policy has an delayed effect on $\beta$.





##Prediction

Calculate $I(t+1) = \beta(t) *S(t)*I(t)$ and $R(t+1) = \sum_i{\gamma_i * I(t-i)}$, $Infection\:Growth=I(t+1)-R(t+1)$


